/**
 * Centralized Platform Event Catalog for Zibonbaba.com
 * Authoritative event types for cross-portal real-time synchronization.
 */

export enum PlatformEventType {
  // --- User & Account Events ---
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_STATUS_UPDATED = 'USER_STATUS_UPDATED',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // --- Product & Catalog Events ---
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_STATUS_UPDATED = 'PRODUCT_STATUS_UPDATED',
  PRODUCT_PRICE_UPDATED = 'PRODUCT_PRICE_UPDATED',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',

  // --- Order Lifecycle Events ---
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_PROCESSING = 'ORDER_PROCESSING',
  ORDER_READY_FOR_DELIVERY = 'ORDER_READY_FOR_DELIVERY',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_IN_TRANSIT = 'ORDER_IN_TRANSIT',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_FAILED = 'ORDER_FAILED',
  ORDER_REATTEMPT = 'ORDER_REATTEMPT',
  ORDER_RETURN_REQUESTED = 'ORDER_RETURN_REQUESTED',
  ORDER_RETURNED = 'ORDER_RETURNED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',

  // --- Delivery Assignment Events ---
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DELIVERY_ACCEPTED = 'DELIVERY_ACCEPTED',
  DELIVERY_PICKED_UP = 'DELIVERY_PICKED_UP',
  DELIVERY_IN_TRANSIT = 'DELIVERY_IN_TRANSIT',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  DELIVERY_REJECTED = 'DELIVERY_REJECTED',

  // --- Financial & Wallet Events ---
  WALLET_UPDATED = 'WALLET_UPDATED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYOUT_CREATED = 'PAYOUT_CREATED',
  PAYOUT_UPDATED = 'PAYOUT_UPDATED',

  // --- Notifications ---
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED'
}

export interface PlatformRealtimePayload<T = any> {
  eventId: string;
  eventType: PlatformEventType | string;
  aggregateType: 'ORDER' | 'PRODUCT' | 'INVENTORY' | 'USER' | 'DELIVERY' | 'WALLET' | 'NOTIFICATION';
  aggregateId: string;
  timestamp: string;
  version?: number;
  channels: string[]; // e.g. ['user:xyz', 'order:1001', 'role:ADMIN']
  data: T;
}
